/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  code_id: number;
}
export type ExecuteMsg = {
  mint_paymaster_account: {
    address: Addr;
  };
};
export type Addr = string;
export type QueryMsg = {
  get_paymaster_address: {
    address: Addr;
  };
};