/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Uint64, Addr, InstantiateMsg, ExecuteMsg, QueryMsg, Timestamp, ContractInfo } from "./LoanContract.types";
export interface LoanContractMsg {
  contractAddress: string;
  sender: string;
  acceptPayment: ({
    payment
  }: {
    payment: Uint64;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateStatus: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class LoanContractMsgComposer implements LoanContractMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.acceptPayment = this.acceptPayment.bind(this);
    this.updateStatus = this.updateStatus.bind(this);
  }
  acceptPayment = ({
    payment
  }: {
    payment: Uint64;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          accept_payment: {
            payment
          }
        })),
        funds: _funds
      })
    };
  };
  updateStatus = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_status: {}
        })),
        funds: _funds
      })
    };
  };
}